name: ci

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache packages when the branch is not update-dependencies or dependabot/*
      - name: Resolve caching
        id: cache
        if: ${{ github.ref_name != 'update-dependencies' && !startsWith(github.ref_name, 'renovate/') }}
        run: echo "::set-output name=PACKAGE::yarn"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: ${{ steps.cache.outputs.PACKAGE }}
          node-version-file: '.nvmrc'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@moonwalker'

      - run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: yarn lint

  publish:
    needs:
      - lint

    if: contains(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Cache packages when the branch is not update-dependencies or dependabot/*
      - name: Resolve caching
        id: cache
        if: ${{ github.ref_name != 'update-dependencies' && !startsWith(github.ref_name, 'renovate/') }}
        run: echo "::set-output name=PACKAGE::yarn"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: ${{ steps.cache.outputs.PACKAGE }}
          node-version-file: '.nvmrc'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@moonwalker'

      - run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
